// Generated by https://quicktype.io

declare module 'profile.json' {
  export interface Identity {
    name: string;
    title: string;
  }

  export interface Experience {
    title: string;
    company: string;
    location: string;
    dates: string;
    duration: string;
    abstract ? : string;
  }

  export interface Link {
    icon: string;
    url: string;
    name: string;
  }

  export interface Profile {
    links: Link[];
    identity: Identity;
    experience: Experience[];
  }

  const profile: Profile;
  export default profile;
}
