declare module '*.scss';

// Generated by https://quicktype.io

declare module 'profile.json' {
  export interface Identity {
    name: string;
    title: string;
    summary: string;
  }

  export interface Experience {
    title: string;
    company: string;
    location: string;
    dates: string;
    duration: string;
    abstract?: string;
  }

  export interface Education {
    degree: string;
    field: string;
    dates?: string;
    highlight?: string;
  }

  export interface Link {
    icon: string;
    href: string;
    text: string;
  }

  export type Skills = string;

  export interface Endorsment {
    from: string;
    title: string;
    excerpt: string;
  }

  export interface Profile {
    links: Link[];
    identity: Identity;
    experience: Experience[];
    education: Education[];
    endorsments: Endorsment[];
    skills: string[];
  }

  const profile: Profile;
  export default profile;
}
