name: Compile and Publish Resume

on:
  schedule:
    - cron: 0 4 * * * # every day at 4:00 UTC
  release:
    types: published

env:
  resume-file: latest.pdf
  artifact-id: resume

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 22

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          run_install: true

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Verify manual hyphenation
        run: |
          HYPHENATE=yes OUTPUT=l.png pnpm run build && mv dist/l.png .
          HYPHENATE=no  OUTPUT=r.png pnpm run build && mv dist/r.png .
          diff --brief l.png r.png

      - name: Compile PDF
        run: |
          HYPHENATE=no OUTPUT=${{ env.resume-file }} pnpm run build

      - name: Upload resume artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-id }}
          path: dist/${{ env.resume-file }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download resume artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact-id }}

      - name: Create minimalistic index.html
        run: |
          cat << EOF > index.html
          <meta http-equiv="refresh" content="0; URL=./${{ env.resume-file }}">
          EOF

      - name: Compute short SHA
        run: echo SHORT_SHA=`echo ${GITHUB_SHA::7}` >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        # TODO: Consider using the official `deploy-pages` and `upload-pages-artifact` GitHub Actions
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          full_commit_message: Redeploy for ${{ env.SHORT_SHA }}
