name: Compile and Publish Resume

on:
  schedule:
    - cron: 0 4 * * * # every day at 4:00 UTC
  release:
    types: published

env:
  resume-file: resume.pdf
  artifact-id: resume

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 22

    steps:
    - uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        run_install: true

    - name: Install Chrome for Puppeteer
      run: |
        pnpm puppeteer browsers install chrome

    - name: Verify manual hyphenation
      run: |
        pnpm webpack --mode production --env HYPHENATE=yes --env OUTPUT=l.png && mv dist/l.png .
        pnpm webpack --mode production --env HYPHENATE=no  --env OUTPUT=r.png && mv dist/r.png .
        diff --brief l.png r.png

    - name: Compile PDF
      run: |
        pnpm webpack --mode production --env HYPHENATE=no --env OUTPUT=${{ env.resume-file }}

    - name: Upload resume artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact-id }}
        path: dist/${{ env.resume-file }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download resume artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.artifact-id }}

    - name: Create minimalistic index.html
      run: |
        cat << EOF > index.html
        <meta http-equiv="refresh" content="0; URL=./${{ env.resume-file }}">
        EOF

    - name: Compute short SHA
      run: echo SHORT_SHA=`echo ${GITHUB_SHA::7}` >> $GITHUB_ENV

    - name: Deploy to GitHub Pages
      # TODO: Consider using the official `deploy-pages` and `upload-pages-artifact` GitHub Actions
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: .
        github_token: ${{ secrets.GITHUB_TOKEN }}
        full_commit_message: Redeploy for ${{ env.SHORT_SHA }}
