name: Compile and Publish Resume

on:
  release:
    types: published

env:
  resume-file: ccjmne-resume.pdf
  artifact-id: ccjmne-resume

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 16.x

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Webpack build
      run: |
        npm install
        npx webpack --mode production

    - name: Upload resume artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact-id }}
        path: dist/${{ env.resume-file }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download resume artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.artifact-id }}

    - name: Create minimalistic index.html
      run: |
        cat << EOF > index.html
        <meta http-equiv="refresh" content="0; URL=./${{ env.resume-file }}">
        EOF

    - name: Compute short SHA
      run: echo SHORT_SHA=`echo ${GITHUB_SHA::7}` >> $GITHUB_ENV

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        github_token: ${{ secrets.GITHUB_TOKEN }}
        full_commit_message: Redeploy for ${{ env.SHORT_SHA }}
